spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:~/bibbi;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379

#logging:
#  level:
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  external-urls:
    slack-webhook: https://www.naver.com
  token:
    secret-key: thisiskeyfortestpurpose0101010101010thisiskeyfortestpurpose0101010101010
  web:
    versionFilterEnabled: false
    url-whitelists:
      - /actuator/**
      - /swagger-ui.html
      - /v1/auth/social/**
      - /v1/auth/refresh
      - /v1/auth/force-token
      - /swagger-ui/**
      - /v3/api-docs/**
      - /v3/api-docs
      - /error
      - /v1/links/*
      - /v1/me/app-version
      - /h2-console/**
      - /v1/posts/123

cloud:
  ncp:
    region: ${OBJECT_STORAGE_REGION}
    end-point: ${OBJECT_STORAGE_END_POINT}
    access-key: ${OBJECT_STORAGE_ACCESS_KEY}
    secret-key: ${OBJECT_STORAGE_SECRET_KEY}
    storage:
      bucket: ${OBJECT_STORAGE_BUCKET_NAME}
    image-optimizer-cdn: https://y3snov831909.edge.naverncp.com/CJoP2Lj4Fk
